### ISSUE TITLE
Better word for Glossary in Kannada

### ISSUE THREAD

**Issue by kumiDa** [alar-dict/alar.ink#3]
I noticed `ಪದಗಳ ಗ್ಲಾಸರಿ (Glossary)` used in the footer section of the search dialog page.
Found a few sources suggesting `ಶಬ್ದಸಂಗ್ರಹ`(Definition: an alphabetical list of technical terms in some specialized field of knowledge; usually published as an appendix to a text on that field ) to be the word for glossary in kannada and the definition also seemed apt.

Please do consider this and share your thoughts, I would be happy to submit the changes for this.
Kudos to your efforts!

**Comment by knadh** [comment]
Sounds good @rahul-kumi. You can submit a PR.

**Comment by kumiDa** [comment]
created PR #4 to resolves this issue.

**Comment by kumiDa** [comment]
I also noticed that this can be another word that can be added to the dictionary, should this be reviewed by V.Krishna before it can be included?
@knadh, how do you suggest I proceed?

**Comment by askamist** [comment]
I think ಕೋಶ is the actual Kannada equivalent of glossary. and you can use ಪದಕೋಶ / ಶಬ್ದಕೋಶ in that place, and I personally feel ಪದಕೋಶ would be more appropriate here.

**Comment by knadh** [comment]
@askamist `ಪದಕೋಶ (pada kōśa)` seems to be the most appropriate term. I concur.

**Comment by knadh** [comment]
https://github.com/alar-dict/alar.ink/commit/e9b7cc12a48628b92bf8ba0836d4e243da026d29 closes this.
